In [8]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if employees else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits

# Creating instances of Employee class
employees = [
    Employee("John Doe", "Family A", 50000, "HR"),
    Employee("Jane Smith", "Family B", 60000, "IT"),
    Employee("Michael Johnson", "Family C", 55000, "Finance")
]

# Creating instances of FulltimeEmployee class
fulltime_employees = [
    FulltimeEmployee("Alice Williams", "Family D", 70000, "Marketing", "Healthcare"),
    FulltimeEmployee("Robert Brown", "Family E", 75000, "Engineering", "Retirement plan")
]

# Calling member functions
all_employees = employees + fulltime_employees
avg_salary = Employee.average_salary(all_employees)
print("Average Salary:", avg_salary)

print("Total Number of Employees:", Employee.num_employees)


Average Salary: 62000.0
Total Number of Employees: 5


In [9]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the vector into a 4x5 array
reshaped_array = random_vector.reshape(4, 5)

# Find the indices of the maximum value in each row
max_indices = np.argmax(reshaped_array, axis=1)

# Replace the maximum value in each row with 0
for row_idx, col_idx in enumerate(max_indices):
    reshaped_array[row_idx, col_idx] = 0

print("Original random vector:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)

Original random vector:
[14.32824285  5.00441458  2.36507787 10.99909011  0.         15.9689547
 16.12036993 16.51559789  0.          3.00194166 14.09089285  9.33881775
  0.          8.11863376 16.03492258  6.55390152  0.          8.49964776
 18.77816863 15.69011743]

Reshaped array:
[[14.32824285  5.00441458  2.36507787 10.99909011  0.        ]
 [15.9689547  16.12036993 16.51559789  0.          3.00194166]
 [14.09089285  9.33881775  0.          8.11863376 16.03492258]
 [ 6.55390152  0.          8.49964776 18.77816863 15.69011743]]
